default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cruncher_development
  username: postgres
  password: postgres
test:
  <<: *default
  database: cruncher_test
  username: postgres
  password: postgres

production:
  <<: *default
  database: cruncher_production
  username: cruncher
  password: <%= ENV['CRUNCHER_DATABASE_PASSWORD'] %>
