# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9e4c5f59e2e9e35af6df899b44116cbc0de21919bed347dde6122638af92e6963645ad13475059ee15b7002f8aab9df61819ffb0e2e1724e17e8bfd1e1bc4dfd
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  devise_secret_key: 5faee9819b11c9133f426bca25023e4700ab7ae620164fac46280189f02f98b379fdfdde86e4553e817253b0a27821409264023471151614fbcc9789d38e979a

test:
  secret_key_base: 2e4d3e31443862b7ce39fb9507feb59de8ad4d99595201330f465ced44f955904f66b23a4a4a53d72075febcb6858f8925c6b07ee27f3742da3d3a9846029e98

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  sendgrid_password: <%= ENV["SENDGRID_API_KEY"] %>
  devise_secret_key: <%= ENV["DEVISE_SECRET_KEY"] %>
